global:
  # global.registry -- You can specify the image registry.
  registry: docker.io
  # global.repository -- You can specify the image repository.
  repository: citacloud

image:
  # image.pullPolicy -- You can specify the image pull policy.
  pullPolicy: IfNotPresent
  # image.tag -- You can specify the image tag.
  tag: v0.0.2

# replicas -- You can specify the replica count.
replicas: 1

# serviceAccountName -- You can specify the service account.
serviceAccountName: cita-cloud-operator-proxy-sa