apiVersion: v1
kind: Service
metadata:
  name: cita-cloud-operator-proxy
  labels:
    app.kubernetes.io/component: proxy-server
    {{- include "cita-cloud-operator-proxy.labels" . | nindent 4 }}
spec:
  selector:
    app: cita-cloud-operator-proxy
    {{- include "cita-cloud-operator-proxy.selectorLabels" . | nindent 4 }}
  type: NodePort
  sessionAffinity: None
  ports:
  - name: proxy-server
    protocol: TCP
    port: 8090
    targetPort: 8090